version: '3'
services:
  basevar:
    build:
      context: ./
    restart: always
    container_name: caster_basevar
    ports:
      - 9999:9999
    tty: true
    environment:
      - APIKEY
      - USERID
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
