
version: '3'
volumes:
  postgiswmaps:
services:
#swmaps
  postgiswmaps:
    image: kartoza/postgis:13-3.1
    restart: always
    container_name: postgiswmap
    ports:
      - 8080:5432
    environment:
      - POSTGRES_USER=swmaps
      - POSTGRES_PASS=swmaps123?
      - POSTGRES_DBNAME=swmap
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
      - SHARED_PRELOAD_LIBRARIES=pg_cron
      - REPLICATION=true
#      - REPLICATION_USER
#      - REPLICATION_PASS
    restart: always
    entrypoint: >  #get IGN raf18b grid for proj 7.2.1 and change caster_conf group before starting
       bash -c 'FILE=/usr/share/proj/fr_ign_RAF18.tif &&
                if [[ -f "$FILE" ]];
                  then echo "$FILE exists.";
                  else wget https://cdn.proj.org/fr_ign_RAF18b.tif -O /usr/share/proj/fr_ign_RAF18.tif;
                fi;
                chown -R :102 /home;
                ./docker-entrypoint.sh'
    volumes:
      - postgiswmaps:/var/lib/postgresql
      - ./caster_conf:/home
      - ./pg_backup:/srv #db backup accesibility
#      - ./pg_backup/centipede/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql #make db at first boot
    healthcheck:
      test: "exit 0"
