{
 "title": "Centipede_log_base",
 "description": "Centipede RTK Base Logs Monitoring",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "mount_name", "label": "Mount Name", "query": "select mp from antenne" }
  ]
 },
 "panels": [
  {
   "title": "Etat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\netat\nFROM etat_1_2\nWHERE\n  mp =  ($mount_name)\n--ORDER BY 1"
    }
   ]
  },
  {
   "title": "Caractéristiques",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  mp as \"MP\",\n  date_declar as \"Déclaration\",\n  receiver,\n  version,\n  antenne\nFROM antenne\nWHERE\n  antenne.mp in ($mount_name)\n"
    }
   ]
  },
  {
   "title": "Deconnexion depuis:",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  control AS \"Date de déconnexion\",\n  mp AS \"Base GNSS\",\n  ti AS \"Durée\"\nFROM defaut_reseau_20s\nWHERE\n  mp =  ($mount_name)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "coupures >= 1h",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  mp ,\n  defaut AS \"time1\",\n  defaut + defaut_persist::interval as \"time2\",\n  defaut_persist,\n  'X' as \"color\"\nFROM defaut_logs\nWHERE\n  $__timeFilter(defaut) AND\n  defaut_logs.mp in ($mount_name) AND\n  defaut_persist >  interval '59 minute'\nunion \nSELECT\n  mp ,\n  defaut AS \"time1\",\n  defaut + defaut_persist::interval as \"time2\",\n  defaut_persist,\n  'X' as \"color\"\nFROM defaut\nWHERE\n  $__timeFilter(defaut) AND\n  defaut.mp in ($mount_name) AND\n  defaut_persist >  interval '1 minute'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Microcoupures > 1min < 1h",
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  defaut AS \"time\",\n  mp AS metric,\n  minu\nFROM defaut_day\nWHERE\n  $__timeFilter(defaut) \n  AND defaut_day.mp in ($mount_name)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Microcoupures < 1min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "secondes" } },
   "yaxes": [
    { "format": "secondes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  defaut AS \"time\",\n  mp AS metric,\n  sec\nFROM defaut_day\nWHERE\n  $__timeFilter(defaut) AND\n  sec != 0 \n  AND defaut_day.mp in ($mount_name)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "GNSS & Messages RTCM3",
   "type": "table",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  mp as \"MP\",\n  navsys,\n  formatd\nFROM antenne\nWHERE\n  antenne.mp in ($mount_name)\n"
    }
   ]
  },
  {
   "title": "Situation",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 18 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  --check_activite AS \"time\",\n  mp,\n  longitude,\n  latitude,\n  case\n    WHEN ping = 'active' THEN 1\n    WHEN ping = 'eteinte' THEN 0\n  end AS etat\nFROM etat_antennes\nWHERE\n--  $__timeFilter(check_activite)\n  etat_antennes.mp in ($mount_name)\nORDER BY 1,2"
    }
   ]
  }
 ]
}